version: '2'

services:
  server:
    image: 'ticketing:latest'
    build:
      context: .
    container_name: server
    depends_on:
      - db
      - keycloak
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mysecretpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_REALM=ticketing
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_URL=http://keycloak:8080
      - JWT_AUTH_CONVERTER_RESOURCE-ID=ticketingclient
    ports:
      - "8080:8080"
  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ../resources/pg_dump.sql:/docker-entrypoint-initdb.d/pg_dump.sql
  keycloak:
    image: 'quay.io/keycloak/keycloak:21.1.1'
    container_name: keycloak
    command: 'start-dev --import-realm'
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8081:8080"
    volumes:
      - ../resources/keycloak_settings:/opt/keycloak/data/import
